import { useCallback, useEffect, useState } from "react";
import { z } from "zod";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Building2, Edit3, Loader2, MapPin, Plus, RefreshCw, ShieldAlert, Users } from "lucide-react";
import { toast } from "sonner";
import { AppLayout } from "@/components/layout/AppLayout";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { authService, canManageMembers, type SignedInProfile } from "@/services/auth";
import { groupService, type MinistryGroup } from "@/services/groups";
import { isSupabaseConfigured } from "@/services/supabase";
import type { AreaOption } from "@/types/database";
import { ICON_SIZE } from "@/lib/icon-sizes";

const schema = z.object({ name: z.string().trim().min(2, "กรุณากรอกชื่อกลุ่ม"), area_id: z.string().uuid("กรุณาเลือกพื้นที่"), meeting_day: z.string().max(50).optional(), meeting_time: z.string().max(20).optional(), location: z.string().max(200).optional(), notes: z.string().max(1000).optional(), status: z.enum(["active", "inactive", "pending", "closed"]) });
type Values = z.infer<typeof schema>;
const statusLabel: Record<Values["status"], string> = { active: "กำลังดำเนินการ", inactive: "ไม่ใช้งาน", pending: "รอเปิดกลุ่ม", closed: "ปิดกลุ่ม" };

function GroupForm({ group, areas, onClose, onSaved }: { group?: MinistryGroup; areas: AreaOption[]; onClose: () => void; onSaved: () => Promise<void> }) {
 const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { name: group?.name ?? "", area_id: group?.area_id ?? "", meeting_day: group?.meeting_day ?? "", meeting_time: group?.meeting_time ?? "", location: group?.location ?? "", notes: group?.notes ?? "", status: group?.status ?? "active" } });
 const onSubmit = form.handleSubmit(async (value) => { try { if (group) await groupService.update(group.id, value); else await groupService.create(value); toast.success(group ? "บันทึกการแก้ไขกลุ่มแล้ว" : "เพิ่มกลุ่มพันธกิจแล้ว"); await onSaved(); onClose(); } catch (reason) { toast.error(reason instanceof Error ? reason.message : "ไม่สามารถบันทึกกลุ่มได้"); }});
 return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="group-form-dialog"><DialogHeader><DialogTitle>{group ? "แก้ไขกลุ่มพันธกิจ" : "เพิ่มกลุ่มพันธกิจ"}</DialogTitle><DialogDescription>กลุ่มจะเชื่อมโยงกับพื้นที่เสมอ เพื่อให้รายงานและสมาชิกมีความสัมพันธ์ที่ถูกต้อง</DialogDescription></DialogHeader><form className="member-form" onSubmit={onSubmit}><div className="member-form-grid"><label className="member-field required"><span>ชื่อกลุ่ม</span><input {...form.register("name")} autoFocus />{form.formState.errors.name && <small>{form.formState.errors.name.message}</small>}</label><label className="member-field required"><span>พื้นที่</span><select {...form.register("area_id")}><option value="">เลือกพื้นที่</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select>{form.formState.errors.area_id && <small>{form.formState.errors.area_id.message}</small>}</label><label className="member-field"><span>วันนัดพบ</span><input {...form.register("meeting_day")} placeholder="เช่น วันอังคาร" /></label><label className="member-field"><span>เวลา</span><input type="time" {...form.register("meeting_time")} /></label><label className="member-field full"><span>สถานที่</span><input {...form.register("location")} /></label><label className="member-field"><span>สถานะ</span><select {...form.register("status")}>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="member-field full"><span>บันทึก</span><textarea rows={3} {...form.register("notes")} /></label></div><footer className="member-form-actions"><button type="button" className="cancel-button" onClick={onClose}>ยกเลิก</button><button type="submit" className="blue-button" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? <><Loader2 className="spin" size={14} /> กำลังบันทึก</> : "บันทึกกลุ่ม"}</button></footer></form></DialogContent></Dialog>;
}

export default function Groups() {
 const [profile, setProfile] = useState<SignedInProfile | null | undefined>(undefined); const [groups, setGroups] = useState<MinistryGroup[]>([]); const [areas, setAreas] = useState<AreaOption[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<MinistryGroup | null | undefined>(undefined);
 const canManage = canManageMembers(profile?.role);
 const load = useCallback(async () => { if (!profile) return; setLoading(true); setError(null); try { const [nextGroups, nextAreas] = await Promise.all([groupService.list(), groupService.areas()]); setGroups(nextGroups); setAreas(nextAreas); } catch (reason) { setError(reason instanceof Error ? reason.message : "ไม่สามารถโหลดกลุ่มพันธกิจได้"); } finally { setLoading(false); } }, [profile]);
 useEffect(() => { if (!isSupabaseConfigured) { setProfile(null); return; } void authService.currentProfile().then(setProfile).catch((reason) => { setProfile(null); setError(reason instanceof Error ? reason.message : "ไม่สามารถตรวจสอบสิทธิ์ได้"); }); }, []); useEffect(() => { void load(); }, [load]);
 const message = !isSupabaseConfigured ? "ตั้งค่า Supabase และใช้ migration ก่อนจัดการกลุ่มพันธกิจ" : profile === undefined ? "กำลังตรวจสอบสิทธิ์…" : !profile ? "กรุณาเข้าสู่ระบบด้วยบัญชีที่ได้รับสิทธิ์" : null;
 return <AppLayout><div className="page-heading"><div><span className="eyebrow blue-eyebrow">MINISTRY GROUPS</span><h1>กลุ่มพันธกิจ</h1><p>เชื่อมโยงกลุ่มกับพื้นที่ สมาชิก และรายงานประจำสัปดาห์</p></div>{canManage && <button className="primary-action" onClick={() => setEditing(null)}><Plus size={ICON_SIZE.sm} /> เพิ่มกลุ่ม</button>}</div>{message ? <section className="data-state-card card-surface"><ShieldAlert size={32}/><h2>ยังไม่พร้อมใช้งาน</h2><p>{message}</p></section> : error ? <section className="data-state-card card-surface"><ShieldAlert size={32}/><h2>ไม่สามารถโหลดข้อมูลได้</h2><p>{error}</p><button className="blue-button" onClick={() => void load()}><RefreshCw size={14}/> ลองอีกครั้ง</button></section> : loading ? <div className="group-grid group-loading">{Array.from({length: 4}).map((_, i) => <div key={i} className="card-surface"/>)}</div> : <section className="group-grid">{groups.length ? groups.map((group) => <article className="group-card card-surface" key={group.id}><div className="group-card-icon"><Users size={ICON_SIZE.lg}/></div><div className="group-card-head"><span className={`status-chip ${group.status === "active" ? "good" : "attention"}`}>{statusLabel[group.status]}</span>{canManage && <button className="row-menu" onClick={() => setEditing(group)} aria-label={`แก้ไข ${group.name}`}><Edit3 size={ICON_SIZE.sm}/></button>}</div><h2>{group.name}</h2><p><MapPin size={ICON_SIZE.sm}/>{group.area?.name || "ไม่ระบุพื้นที่"}</p><p><Building2 size={ICON_SIZE.sm}/>{[group.meeting_day, group.meeting_time, group.location].filter(Boolean).join(" · ") || "ยังไม่ระบุตารางนัดพบ"}</p></article>) : <div className="empty-members card-surface"><Users size={32}/><h3>ยังไม่มีกลุ่มพันธกิจ</h3><p>สร้างกลุ่มแรกหลังจากตั้งค่าพื้นที่แล้ว</p></div>}</section>}{editing !== undefined && <GroupForm group={editing ?? undefined} areas={areas} onClose={() => setEditing(undefined)} onSaved={load}/>}</AppLayout>;
}
