import { useMemo, useState, type CSSProperties } from "react";
import { Link, useLocation } from "wouter";
import { ArrowRight, Bell, Building2, CalendarDays, ChevronDown, ChevronRight, Church, FileText, Heart, Menu, Search, Sparkles, Target, Users, X } from "lucide-react";
import { navItems } from "../data/mockData";
import { usePuntakitDashboard } from "../hooks/usePuntakitDashboard";
import type { AccentTone, ChurchActivity, DashboardSnapshot, JourneyStage } from "../types/puntakit";

function Sidebar({ mobileOpen, onClose }: { mobileOpen: boolean; onClose: () => void }) {
  const [location] = useLocation();
  return <aside className={`sidebar ${mobileOpen ? "is-open" : ""}`} aria-label="เมนูหลัก">
    <div className="sidebar-brand"><div className="brand-mark"><Church size={25} strokeWidth={2.4} /></div><div><div className="brand-name">Puntakit</div><div className="brand-sub">CHURCH</div></div><button className="icon-button mobile-close" onClick={onClose} aria-label="ปิดเมนู"><X size={20} /></button></div>
    <div className="sidebar-section-label">พื้นที่ของคริสตจักร</div>
    <nav className="sidebar-nav">{navItems.map(({ label, href, icon: Icon }) => { const active = location === href; return <Link key={href} href={href} className={`nav-item ${active ? "active" : ""}`} onClick={onClose}><Icon size={19} strokeWidth={active ? 2.5 : 2} /><span>{label}</span>{active && <span className="nav-dot" />}</Link>; })}</nav>
    <div className="sidebar-spacer" /><div className="sidebar-verse"><div className="verse-leaf">✦</div><p>“รักพระเจ้า<br />รักผู้คน<br />เปลี่ยนแปลงชุมชน”</p><span>พันธกิจของเรา</span></div><div className="sidebar-footer"><div className="footer-cross">✝</div><span>บ้านของทุกคน</span></div>
  </aside>;
}

function Topbar({ query, results, onQueryChange, onMenu }: { query: string; results: Array<{ type: string; title: string; meta: string; href: string }>; onQueryChange: (value: string) => void; onMenu: () => void }) {
  const [notiOpen, setNotiOpen] = useState(false);
  return <header className="topbar"><button className="icon-button menu-button" onClick={onMenu} aria-label="เปิดเมนู"><Menu size={22} /></button><div className="search-wrap"><label className="search-box"><Search size={19} /><input value={query} onChange={(e) => onQueryChange(e.target.value)} placeholder="ค้นหาสมาชิก กิจกรรม หรือประกาศ..." aria-label="ค้นหา" /></label>{query && <div className="search-results" role="listbox">{results.length ? results.map((result) => <Link key={`${result.type}-${result.title}`} href={result.href} className="search-result"><span>{result.type}</span><strong>{result.title}</strong><small>{result.meta}</small></Link>) : <div className="search-empty">ไม่พบข้อมูลที่ตรงกัน</div>}</div>}</div><div className="topbar-right"><div className="notification-wrap"><button className="icon-button notification-button" onClick={() => setNotiOpen((v) => !v)} aria-label="การแจ้งเตือน"><Bell size={20} /><span className="notification-badge">3</span></button>{notiOpen && <div className="notification-popover"><strong>การแจ้งเตือน</strong><span>มีสมาชิกใหม่ 3 คนรอการติดตาม</span><span>กิจกรรมกลุ่มบ้านเริ่มใน 2 ชั่วโมง</span></div>}</div><div className="top-divider" /><div className="profile"><div className="avatar">น</div><div><strong>ยินดีต้อนรับ</strong><span>ทีมพันธกิจ</span></div><ChevronDown size={16} className="profile-chevron" /></div></div></header>;
}

function HeroBanner() { return <section className="hero-card"><img src="/manus-storage/puntakit-hero_22958e7d.jpg" alt="สมาชิกคริสตจักรใช้เวลาร่วมกัน" /><div className="hero-overlay" /><div className="hero-copy"><div className="eyebrow"><span /> เป้าหมายของเรา</div><h1>1 คน นำ 2 คน<br /><em>สู่พระคริสต์</em><br />และคริสตจักร</h1><p>“เพราะคริสตจักร คือ บ้านของทุกคน”</p><small>มัทธิว 28:19–20</small></div><div className="hero-callout"><Sparkles size={18} /><strong>มาร่วมกัน<br />สร้างสาวกว่า<br />ให้เติบโตในพระเจ้า</strong><button>เริ่มต้นวันนี้ <ArrowRight size={15} /></button></div></section>; }

function StatCard({ metric }: { metric: DashboardSnapshot["stats"][number] }) { const Icon = metric.icon; return <Link href={metric.href} className={`stat-card ${metric.tone}`} aria-label={`ดู${metric.label}`}><div className="stat-top"><div className="stat-icon"><Icon size={21} /></div><span className="stat-action"><ArrowRight size={16} /></span></div><span className="stat-label">{metric.label}</span><strong className="stat-value">{metric.value.toLocaleString("th-TH")} {metric.suffix}</strong><span className="stat-detail"><b>{metric.trend}</b> {metric.detail}</span></Link>; }

function Journey({ stages }: { stages: JourneyStage[] }) { const [selected, setSelected] = useState(stages[0]); return <section className="surface journey-card"><div className="section-heading"><div><span className="kicker">เส้นทางการเติบโต</span><h2>6 ขั้นตอนสู่การสร้างสาวก</h2></div><button className="text-button">ดูภาพรวม <ArrowRight size={15} /></button></div><div className="journey-track">{stages.map((item, index) => { const Icon = item.icon; return <div className="journey-step-wrap" key={item.id}><button className={`journey-step ${item.tone} ${selected.id === item.id ? "selected" : ""}`} onClick={() => setSelected(item)} aria-pressed={selected.id === item.id}><div className="journey-number">{item.number}</div><div className="journey-thumb"><img src={item.image} alt="" style={{ objectPosition: item.imagePosition }} /><div className="journey-thumb-icon"><Icon size={16} /></div></div><strong>{item.title}</strong><span>{item.detail}</span></button>{index < stages.length - 1 && <ChevronRight className="journey-arrow" size={21} />}</div>; })}</div><div className="journey-detail"><div className="journey-detail-icon"><selected.icon size={19} /></div><div><strong>{selected.title}</strong><p>{selected.description}</p></div><span>{selected.count} คน</span></div></section>; }

function GoalCard({ goal }: { goal: DashboardSnapshot["goal"] }) { const percent = Math.round((goal.current / goal.target) * 100); return <section className="surface goal-card"><div className="section-heading compact"><div><span className="kicker">เป้าหมายร่วมกัน</span><h2>เป้าหมาย 2026</h2></div><Target size={22} className="goal-target" /></div><div className="goal-ring" style={{ "--progress": `${percent * 3.6}deg` } as CSSProperties}><div><strong>{goal.target.toLocaleString("th-TH")}</strong><span>คน<br />{goal.label}</span></div></div><div className="goal-legend"><div><span className="legend-dot green" /><span>ปัจจุบัน</span><b>{goal.current.toLocaleString("th-TH")} คน <small>({percent}%)</small></b></div><div><span className="legend-dot pink" /><span>ยังขาด</span><b>{(goal.target - goal.current).toLocaleString("th-TH")} คน <small>({100 - percent}%)</small></b></div></div></section>; }

function Activities({ items }: { items: ChurchActivity[] }) { const [selected, setSelected] = useState<ChurchActivity | null>(null); return <section className="surface activities-card"><div className="section-heading compact"><div><span className="kicker">ความเคลื่อนไหว</span><h2>กิจกรรมล่าสุด</h2></div><button className="text-button">ดูทั้งหมด <ArrowRight size={15} /></button></div><div className="activity-list">{items.map((item) => { const Icon = item.icon; return <button className="activity-item" key={item.id} onClick={() => setSelected(item)}><div className={`activity-icon ${item.tone}`}><Icon size={17} /></div><div className="activity-content"><strong>{item.title}</strong><span>{item.meta}</span></div><time>{item.time}</time></button>; })}</div>{selected && <div className="activity-detail"><div><strong>{selected.title}</strong><span>{selected.detail}</span></div><button onClick={() => setSelected(null)} aria-label="ปิดรายละเอียด"><X size={15} /></button></div>}</section>; }

function StatusAndChart({ snapshot }: { snapshot: DashboardSnapshot }) { const max = useMemo(() => Math.max(...snapshot.distribution.map((d) => d.value)), [snapshot.distribution]); return <div className="bottom-grid"><section className="surface status-card"><div className="section-heading compact"><div><span className="kicker">ภาพรวมสุขภาพคริสตจักร</span><h2>สรุปสถานะปัจจุบัน</h2></div><span className="date-chip">13 ก.ย. 2026</span></div><div className="status-grid">{snapshot.status.map((metric) => { const Icon = metric.icon; return <div className={`status-tile ${metric.tone}`} key={metric.label}><Icon size={20} /><span>{metric.label}</span><strong>{metric.value.toLocaleString("th-TH")} <small>คน</small></strong><em>เป้าหมาย {metric.target.toLocaleString("th-TH")} คน</em></div>; })}</div><div className="status-total"><span>รวมทั้งหมด</span><strong>{snapshot.status.reduce((sum, metric) => sum + metric.value, 0).toLocaleString("th-TH")} <small>คน</small></strong></div></section><section className="surface chart-card"><div className="section-heading compact"><div><span className="kicker">ข้อมูลเพื่อการดูแล</span><h2>สมาชิกตามพื้นที่</h2></div><button className="select-button">ทั้งหมด <ChevronDown size={15} /></button></div><div className="bars" role="img" aria-label="กราฟสมาชิกตามพื้นที่">{snapshot.distribution.map((point) => <div className="bar-column" key={point.label}><span className="bar-value">{point.value}</span><div className={`bar ${point.tone}`} style={{ height: `${(point.value / max) * 100}%` }} /><span className="bar-label">{point.label}</span></div>)}</div></section></div>; }

function MissionBanner() { return <section className="mission-banner"><img src="/manus-storage/puntakit-mission_49f2fd20.jpg" alt="พระคัมภีร์และแสงอาทิตย์" /><div className="mission-overlay" /><div className="mission-copy"><span>พระบัญชาที่ยังดำเนินต่อไป</span><h2>“ไปทั่วโลก<br />และประกาศข่าวประเสริฐ<br />แก่คนทั้งปวง”</h2><small>มัทธิว 28:19</small></div></section>; }

function LoadingDashboard() { return <main className="dashboard"><div className="loading-state"><div className="loading-orb" /><h2>กำลังเตรียมภาพรวมของคริสตจักร</h2><p>กำลังโหลดข้อมูลผู้คนและกิจกรรมล่าสุด...</p></div></main>; }

export default function Home() { const [mobileOpen, setMobileOpen] = useState(false); const { data, loading, query, setQuery, results } = usePuntakitDashboard(); return <div className="app-shell"><Sidebar mobileOpen={mobileOpen} onClose={() => setMobileOpen(false)} /><div className={`shell-main ${mobileOpen ? "dimmed" : ""}`}><Topbar query={query} results={results} onQueryChange={setQuery} onMenu={() => setMobileOpen(true)} />{loading || !data ? <LoadingDashboard /> : <main className="dashboard"><div className="welcome-row"><div><span className="kicker">วันอาทิตย์ที่ 13 กันยายน 2026</span><h1>สวัสดีครับ ทีมพันธกิจ <span>✦</span></h1><p>มาดูกันว่า วันนี้เราจะดูแลผู้คนให้เติบโตได้อย่างไร</p></div><button className="primary-button"><CalendarDays size={17} /> บันทึกกิจกรรม <ChevronRight size={16} /></button></div><div className="dashboard-grid"><div className="main-column"><HeroBanner /><div className="stat-grid">{data.stats.map((metric) => <StatCard key={metric.id} metric={metric} />)}</div><Journey stages={data.journey} /><StatusAndChart snapshot={data} /></div><div className="side-column"><section className="surface mission-card"><div className="mission-card-top"><span className="kicker">หัวใจของพันธกิจ</span><div className="plant">✦</div></div><h2>พันธกิจบ้าน<br />คือ ฐานสร้างคน</h2><p>คริสตจักร คือ บ้านแห่งการผูกพัน เติบโต และรับใช้</p><button className="outline-button">อ่านเพิ่มเติม <ArrowRight size={15} /></button></section><GoalCard goal={data.goal} /><Activities items={data.activities} /><MissionBanner /></div></div></main>}</div></div>; }

export { Sidebar, Topbar };
